apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana
  namespace: kube-monitoring
  labels:
    name: grafana
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: grafana
