apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster-v1
  namespace: kube-monitoring
  labels:
    name: heapster
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: heapster
        version: v1
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v1.1.0
          name: heapster
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 80m
              memory: 140Mi
            requests:
              cpu: 80m
              memory: 140Mi
          command:
            - /heapster
            - --source=kubernetes.summary_api:''
            - --sink=influxdb:http://monitoring-influxdb:8086
        # https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/influxdb/heapster-controller.yaml#L56

        # https://github.com/kubernetes/contrib/tree/master/addon-resizer
        - image: gcr.io/google_containers/addon-resizer:1.3
          name: heapster-nanny
          resources:
            limits:
              cpu: 50m
              memory: 90Mi
            requests:
              cpu: 50m
              memory: 90Mi
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --cpu=80m
            - --extra-cpu=0.5m
            - --memory=140Mi
            - --extra-memory=4Mi
            - --threshold=5
            - --deployment=heapster-v1
            - --container=heapster
            - --poll-period=300000
            - --estimator=exponential
