apiVersion: v1
kind: Service
metadata:
  name: monitoring-heapster
  namespace: kube-monitoring
  labels:
    name: heapster
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    name: heapster
