apiVersion: v1
kind: Service
metadata:
  name: monitoring-influxdb
  namespace: kube-monitoring
  labels:
    name: influxdb
spec:
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
      name: admin-ui
    - port: 8086
      protocol: TCP
      targetPort: 8086
      name: api
  selector:
    name: influxdb
